apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dmlvm4pqh-nodejs
  janus-idp.io/tekton: dmlvm4pqh-nodejs
  backstage.io/kubernetes-id: dmlvm4pqh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dmlvm4pqh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
