apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dmlvm4pqh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dmlvm4pqh-nodejs 
  name: dmlvm4pqh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dmlvm4pqh-nodejs 
